---
# tasks file for osp-get-images
# Show all available Openstack images
- name: Select all available Openstack images
  openstack.cloud.image_info:
  register: result

- name: Show images
  debug:
    msg: "{{ item.name }}"
  with_items: "{{ result.image }}"
