---
# tasks file for osp16-network

- name: create tenant network
  os_network:
    state: present
    name: demo-net

- name: create subnet
  os_subnet:
    state: present
    network_name: demo-net
    name: demo-subnet
    cidr: 10.10.10.0/24

- name: create router
  os_router:
    state: present
    name: demo-router
    network: external
    interfaces:
      - demo-subnet
