---
# tasks file for osp16-securitygroup

- name: create security group
  os_security_group:
    state: present
    name: sg-demo
    description: security group for demo project

- name: add rules to secrurity group
  os_security_group_rule:
    security_group: sg-demo
    protocol: tcp
    port_range_min: "{{ item.port }}"
    port_range_max: "{{ item.port }}"
    remote_ip_prefix: "{{ item.ip_prefix }}"
  with_items:
    - { port: '8080', ip_prefix: '0.0.0.0/0' }
    - { port: '22', ip_prefix: '0.0.0.0/0' }
