---
# tasks file for osp16-securitygroup

- os_security_group:
    cloud: mordred
    state: present
    name: foo
    description: security group for foo servers

- os_security_group_rule:
    cloud: mordred
    security_group: foo
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

