---
# tasks file for osp16-keypair

  - name: Generate key files
    user:
      name: "{{ ansible_env.USER }}"
      generate_ssh_key: yes
      ssh_key_file: .ssh/ansible_id_rsa

  - name: Create keypair
    os_keypair:
      state: present
      name: ansible_key
      project: demo
      public_key_file: "{{ ansible_env.HOME }}/.ssh/ansible_id_rsa.pub"
