---
# tasks file for poc.vm_provision_osp
#

- name: Init yum.repos.d's file
  ansible.builtin.shell: rm -f /etc/yum.repos.d/*.repo

- name: Copy repo file
  ansible.builtin.template:
    src: rhel92.repo.j2
    dest: /etc/yum.repos.d/rhel92.repo

- name: Copy resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

#- name: update system
#  ansible.builtin.package:
#    name: "*"
#    state: latest

- name: Install utility packages
  ansible.builtin.package:
    name: sshpass, dstat, sysstat, net-tools, wget
    state: present